### ISSUE TITLE
Constraint calculation

### ISSUE THREAD

**Issue by yardenas** [jqueeney/robust-safe-rl#1]
Hi!

First, very impressive work, thank you!
I wanted to ask about the constraint computation [here](https://github.com/jqueeney/robust-safe-rl/blob/22b3e93139984cbbb73c1f68aea25d6a759faa37/robust_safe_rl/envs/wrappers/rwrl_wrapper.py#L48).

As far as I understand, the constraint array represents an indicator for each individual constraint in the environment. If that is correct, why do you use `np.all(constraints)` and not `np.any(constraints)`? I guess I'm missing something, but not sure what.

**Comment by jqueeney** [comment]
Thank you for your interest in the repository. In the RWRL Suite, constraints are set as `True` when they are satisfied and `False` when they are violated. For the cost function in `rwrl_wrapper.py`, we set cost equal to 1 if any of the constraints are violated (where `np.all` will return `False`) and cost equal to 0 if all of the constraints are satisfied (by checking that all of the constraints are `True` with `np.all`). Hope this helps!
